Using the LinkPreview API to get the page title
zolrath/obsidian-auto-link-title pull request #128
Opened 2024-10-15 06:19 UTC by ZhymabekRoman

Should fix #124, probably should fix #118, fixes major security problem - #81, closes #77, closes #46, closes #119, closes #116, should fix #114, should fix #93, should fix #41.

Doesn't affect #122

2024-11-07 16:14 UTC, DylanSpeiser commented
Bumping this, looking forward to the YouTube title fix.

2024-11-10 14:44 UTC, wlo2 commented
Looking forward for YouTube links fix too.

2024-11-23 08:27 UTC, yinsanwen commented
Looking forward

2024-12-04 01:10 UTC, zolrath requested changes
This looks great, definitely an awesome service.
A couple of nitpicks so we don't hit their API unnecessarily but overall looks great!

2024-12-04 01:10 UTC, zolrath commented on main.ts
> +    try {
Looks great!
If we add a check to ensure the `linkPreviewApiKey` is 32 characters long so we don't hit their API with invalid requests when the user hasn't put in an API key I'd be up for merging this!

2024-12-04 01:10 UTC, zolrath commented on settings.ts
> +          this.plugin.settings.linkPreviewApiKey = value;
Also, lets `value.trim()` to remove any erroneous whitespace from the user copy/pasting their API key.

2024-12-04 05:35 UTC, ZhymabekRoman commented
@zolrath Done, waiting for review

2024-12-04 20:57 UTC, zolrath commented
Works great, thanks for working on this! 🔥

2024-12-04 21:00 UTC, merged